"""Build reference-matched, signed layer textures from the Rose Glass render.

This is an asset production script, not a runtime dependency. The four stage
captures are generated by scripts/rose-glass-layer-export.html at 0 seconds.
"""

from pathlib import Path
import json

import numpy as np
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
STAGES = ROOT / "qa/rose-glass-layer-assets"
OUTPUT = ROOT / "kits/rose-glass/assets"
REFERENCE = ROOT / "kits/rose-glass/reference/rose-glass-01-final-4k.jpg"
SIZE = (1080, 1920)


def load(path: Path) -> np.ndarray:
    image = Image.open(path).convert("RGB")
    if image.size != SIZE:
        image = image.resize(SIZE, Image.Resampling.LANCZOS)
    return np.asarray(image, dtype=np.float32)


def save(name: str, array: np.ndarray) -> None:
    Image.fromarray(array.astype(np.uint8), "RGB").save(OUTPUT / name, optimize=True)


def main() -> None:
    stages = [load(STAGES / f"stage-{index}.png") for index in range(4)]
    reference = load(REFERENCE)
    increments = [stages[index] - stages[index - 1] for index in range(1, 4)]
    residual = reference - stages[3]

    # Allocate reference corrections to the frontmost visible object. Source
    # stage differences include each object's shadow and progressive edge, so
    # the weight reaches beyond its hard silhouette without inventing a rim.
    coverage = [np.clip(np.max(np.abs(delta), axis=2, keepdims=True) / 12.0, 0, 1)
                for delta in increments]
    remaining = np.ones((*SIZE[::-1], 1), dtype=np.float32)
    weights = [None, None, None]
    for index in (2, 1, 0):
        weights[index] = remaining * coverage[index]
        remaining *= 1 - coverage[index]
    base_weight = remaining

    corrected = [delta + residual * weight for delta, weight in zip(increments, weights)]
    encoded = [np.clip(np.rint((delta + 255.0) / 2.0), 0, 255).astype(np.uint8)
               for delta in corrected]
    decoded = [texture.astype(np.int16) * 2 - 255 for texture in encoded]
    base = reference.astype(np.int16) - sum(decoded)
    clipped_pixels = np.count_nonzero(np.any((base < 0) | (base > 255), axis=2))
    base = np.clip(base, 0, 255).astype(np.uint8)
    rebuilt = base.astype(np.int16) + sum(decoded)
    error = np.abs(rebuilt - reference.astype(np.int16))

    OUTPUT.mkdir(parents=True, exist_ok=True)
    save("rose-glass-plate-base.png", base)
    for name, texture in zip(("upper", "lower", "foreground"), encoded):
        save(f"rose-glass-delta-{name}.png", texture)
    Image.fromarray(np.clip(rebuilt, 0, 255).astype(np.uint8), "RGB").save(
        STAGES / "reconstruction.png", optimize=True)
    contract = {
        "name": "Rose Glass reference-matched signed layer textures",
        "version": "1.0.0",
        "size": list(SIZE),
        "origin": "top-left",
        "displayMapping": "For a 9:16 output UV measured from top-left, material point p = (uv.x * 720 - 65, uv.y * 1280). Sample layer PNGs at ((p.x + 65) / 720, p.y / 1280). Sample SVG masks at (p.x / 590, p.y / 1280).",
        "colorSpace": "sRGB byte values; decode and composite in sRGB for exact idle reconstruction, then add optional dynamic illumination in linear light",
        "files": ["rose-glass-plate-base.png", "rose-glass-delta-upper.png", "rose-glass-delta-lower.png", "rose-glass-delta-foreground.png"],
        "decode": "base.rgb + (2 * upper.rgb - 255) + (2 * lower.rgb - 255) + (2 * foreground.rgb - 255), where texture RGB is read as 0..255 byte values",
        "shaderDecode": "base + (2.0 * upper - 1.0) + (2.0 * lower - 1.0) + (2.0 * foreground - 1.0); clamp once after all four textures are combined",
        "warp": "Sample each signed delta at that body's inverse-deformed reference point converted through displayMapping to its PNG UV; sample base at unchanged screen point. Keep upper, lower, foreground in depth order for hit testing and highlight placement.",
        "reference": "rose-glass-01-final-4k.jpg downsampled to 1080x1920",
        "sourceStageCapture": "Original WebGL artwork at 0 light seconds, 1080x1920, stages backdrop/upper/lower/foreground",
        "validation": {"meanAbsoluteError8bit": float(error.mean()), "maxAbsoluteError8bit": int(error.max()), "clippedBasePixels": int(clipped_pixels)},
        "limits": ["Signed deltas faithfully reconstruct the static reference but large cross-body overlaps need depth-aware compositing; test a five-pointer drag before shipping."]
    }
    (OUTPUT / "rose-glass-layer-contract.json").write_text(json.dumps(contract, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps(contract["validation"], indent=2))


if __name__ == "__main__":
    main()
